### ISSUE TITLE
[Baekjoon] 11954: NIZOVI

### ISSUE THREAD

**Issue by hyejinhong** [Keep-learning-java/Algorithm-Study#17]
https://www.acmicpc.net/problem/11954

열린 괄호가 나올 때마다 스택에 넣어서
현재 스택의 사이즈만큼 탭을 해주고
닫힌 괄호가 나오면 스택에서 pop 해주는 방식으로 풀었습니다.

```java
public class BOJ_11954 {

    public static void main(String[] args) throws IOException {
        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
        String input = br.readLine();

        Stack<Character> stack = new Stack<>();
        for(int i=0; i<input.length(); i++) {
            char ch = input.charAt(i);

            if(ch == '{') {
                printTab(stack.size());
                stack.push(ch);
                // 앞이 닫는 괄호
                if(i-1 >= 0 && input.charAt(i-1) == '}') {
                    System.out.println();
                }
                System.out.println("{");
            }
            else if(ch == '}') {
                stack.pop();
                // 앞에 열린 괄호면
                if(input.charAt(i-1) != '{' && input.charAt(i-1) != '}') {
                    System.out.println();
                }

                // 앞이 닫힌 괄호면
                if(input.charAt(i-1) == '}') {
                    System.out.println();
                }
                printTab(stack.size());
                System.out.print("}");
            }
            else if(ch == ',') {
                // 앞이 여는 괄호 or 쉼표면 탭
                if(input.charAt(i-1) == '{' || input.charAt(i-1) == ',') {
                    printTab(stack.size());
                }

                System.out.println(',');
            }
            else {
                // 앞이 닫는 괄호인 경우
                if(input.charAt(i-1) == '}') {
                    System.out.println();
                }
                // 앞이 문자가 아닌 경우에 탭
                if(input.charAt(i-1) < 'a' || input.charAt(i-1) > 'z') {
                    printTab(stack.size());
                }

                System.out.print(ch);
            }
        }
    }

    public static void printTab(int count) {
        for(int i=0; i<count; i++) {
            System.out.print("\t");
        }
    }
}
```

:sos: 반례를 찾기가 어려워서 도움 요청드립니다 ㅠ_ㅠ
그리고 너무 하드코딩인 것 같아 코드 개선 방법도 함께 생각해보고 싶습니다...

**Comment by sonsy0929** [comment]
http://boj.kr/21c0eff9350e4898ac1800de5211b38d

로직은 정말 잘 구성하셨는데.. 출력 부분에서 문제가 있습니다. `"\t"`이 아니라 `"  "`로 고쳐야 합니다 ㅠㅠ..
이유는 다음과 같습니다..

- After the curly bracket denoting the beginning of the array, the indentation of the content increases (shifting the output to the right) for **2 spaces.**
- Before the curly bracket denoting the end of the array ’}’, the indentation of the content decreases (shifting the output to the left) for **2 spaces.**

**Comment by sonsy0929** [comment]
리팩토링 부분은.. 이슈를 먼저 봐서 저도 한 번 풀어보고 고민을 해봐야 할 것 같습니다.
재귀로도 풀 수 있을 것 같고.. 괄호가 하나라 굳이 stack을 사용하지 않고 변수 하나로 컨트롤이 가능할 것 같습니다.
case 분류하는 부분은 하드코딩 말고 지금 당장 생각나는 것은 없네요.

**Comment by hyejinhong** [comment]
아아..!!!! ㅠㅠ 문제를 잘 읽겠습니다 감사합니다 ㅠㅠ

**Comment by sonsy0929** [comment]
리팩토링을 고려하여 코드를 구현해보았습니다 !

✍ 괄호가 하나라 Stack을 이용하지 않고 변수 하나로 컨트롤이 가능합니다. 이를 다음과 같이 구현했습니다.
source) http://boj.kr/877d50b8819e426785d81088fd23bdcf 
✍ case 분류를 할 때 if문을 이용한 하드코딩이 아닌 디자인 패턴 중 Factory Pattern과 Strategy Pattern을 이용하여 구현했습니다.
source) http://boj.kr/e8bb1edcbc784f4aae68e3ef8970a504

요새는 알고리즘 문제를 풀 때 빨리 풀려고만 해서 코드 개선 방법에 대한 생각을 하지 못하였는데, 작성해주신 이슈 덕분에 오랜만에 리팩토링에 대해서 고민과 함께 자바에 대해서 공부를 할 수 있는 기회가 되었습니당 😊

제가 참고한 사이트입니다
📕 https://velog.io/@kimjungmin0426/%EB%94%94%EC%9E%90%EC%9D%B8%ED%8C%A8%ED%84%B4-%EC%A0%84%EB%9E%B5%ED%8C%A8%ED%84%B4
📕 https://codechacha.com/ko/java8-functional-interface/

디자인 패턴에 대해서 스터디 이후에 저도 별도로 정리하려고 합니다 !
