### ISSUE TITLE
Java 배열 복사 - 얕은 복사와 깊은 복사

### ISSUE THREAD

**Issue by hyejinhong** [Keep-learning-java/Algorithm-Study#23]
### 👶 얕은 복사 (Shallow Copy)
```java
String[] people = { "hyejin, "daejik", "sangryeol" };
String[] peopleCopy = people;

peopleCopy[0] = "hyejinhong";

System.out.println(people[0]);
```
`result` : `hyejinhong`

얕은 복사는 배열 변수 선언을 통해 복사합니다.
이때 원본 배열의 **주솟값**을 가져옵니다.
그래서 복사한 배열을 수정하면 원본 배열의 데이터도 변경됩니다.

### 💪 깊은 복사 (Deep Copy)
```java
String[] people = { "hyejin, "daejik", "sangryeol" };
String[] peopleCopy = people.clone();

peopleCopy[0] = "hyejinhong";

System.out.println(peopleCopy[0]);
System.out.println(people[0]);
```
`result` : `hyejinhong`
`hyejin`

깊은 복사는 `clone()` 메소드를 사용하여, 데이터를 복사하여 새로운 배열을 생성합니다.
따라서 복사한 배열을 수정해도 원본 배열에는 영향을 미치지 않습니다.

---
**[Baekjoon] 21276: 계보 복원가 호석**
을 풀면서 가계도에 나오는 사람들의 이름을 저장하고
배열의 인덱스를 노드 번호라고 여기면서 풀었습니다.
이름을 사전 순으로 정렬하면 배열의 인덱스가 바뀌기 때문에
사전 순 정렬을 위한 배열을 생성하기 위해 복사하다가 얕은 복사를 하게 되어서 틀리게 되는 현상이 일어나서
정리해보았습니다. 😄

**Comment by sonsy0929** [comment]
문제 푸시고 겪으신 이슈에 대한 깔끔한 정리 감사합니다 !
