### ISSUE TITLE
헷갈립니다!!!

### ISSUE THREAD

**Issue by leedjik** [Keep-learning-java/Algorithm-Study#33]
```java
set<E> s = new HashSet<>();
HashSet<E> hs = new HashSet<>();
```

이 2개의 차이가 뭘까요...?

**Comment by sonsy0929** [comment]
Set은 Interface니까 결국 s나 hs나 HashSet 아닌가요 ?

**Comment by sgk0713** [comment]
Set은 Interface
HashSet 은 구현체

다형성의 장점을 활용하기 위해 Set으로 선언하는 것이 좋아요.
만약 s나 hs 가 TreeSet으로 처리해야될 일이 생긴다면, s는 TreeSet으로 대입이 가능하나 hs는 불가함.
hs처럼 특정 구현체로 선언한 경우, TreeSet 을 대입하기 위해 해당 변수들을 전부 찾아서 수정하거나 HashSet으로 다시 만들어서 대입해야되는 경우가 생길 수 있음.

다른 예로, 어떤 메소드를 만든다고 가정했을 때, 파라미터로 Set을 받게 할지 HashSet을 받게 할지 생각해보면 좀 더 와닿을 것 같네요.

질문한 두줄의 차이라고 한다면
s는 Interface Set에서 선언한 메소드들만 사용할 수 있다. 
hs는 Interface Set에서 선언한 메소드 뿐만 아니라 HashSet에서 구현한 메소드들도 사용할 수 있다(뭐가 있는지는 잘 모르겠음)
정도일듯
