### ISSUE TITLE
[LeetCode] 1712: Ways to Split Array Into Three Subarray

### ISSUE THREAD

**Issue by hyejinhong** [Keep-learning-java/Algorithm-Study#61]
https://leetcode.com/problems/ways-to-split-array-into-three-subarrays/

```java
class Solution {
    public int waysToSplit(int[] nums) {
		// 부분합
		int[] prefixSums = new int[nums.length];
		prefixSums[0] = nums[0];

		for (int i = 1; i < nums.length; i++) {
			prefixSums[i] = prefixSums[i - 1] + nums[i];
		}
		int count = 0;

		// i: left, mid 구분 지점
		for (int i = 0; i < nums.length; i++) {
			int leftSum = prefixSums[i];

			int left = binarySearch(prefixSums, leftSum, i, i + 1, true);
			int right = binarySearch(prefixSums, leftSum, i, i + 1, false);
			if (left == -1 || right == -1)
				continue;

			count += ((right - left + 1) % 1000000007);
		}

		return count;
    }
    
	public int binarySearch(int[] prefixSums, int leftSum, int left, int point, boolean searchingLeft) {
		int l = left + 1;
		int r = prefixSums.length - 1;
		int res = -1;
		
		while (l <= r) {
			int m = (l + r) / 2;

			// 0 ~ left : left
			// left+1 ~ m : mid
			// m+1 ~ end : right
			int midSum = prefixSums[m] - leftSum;
			int rightSum = prefixSums[prefixSums.length - 1] - prefixSums[m];

			if (leftSum <= midSum && midSum <= rightSum) {
				res = m;
				if (searchingLeft) 
                    r = m -1;
				else 
                    l = m + 1;
			} else if (midSum < leftSum) { //
				// midSum 늘려줌
				l = m + 1;
			} else {
				r = m -1;
			}
		}

		return res;
	}
}
```

테스트케이스 (85/88) 통과하는 코드입니다.
걸린 부분이
`int[] nums = { 0, 0, 0, .., 0 };`
`nums`의 모든 원소가 0이고, 길이가 10,000인 경우 인데요.
output : 704982704
expected : 999849973

제 코드는
for문 i로 left의 범위를 고정시켜놓고
mid와 right 조건을 만족하는 개수를 binarySearch로 찾아 count에 더해주고 있는데요.,
왜 저 테스트 케이스에서 걸리는지 잘 모르겠습니다.
숫자가 크다보니 디버깅을 어떻게 해야할 지도 감이 안 오네여. 😢

**Comment by sonsy0929** [comment]
overflow가 발생하는 것 같습니다.
10억 + 7로 modular 연산을 했기 때문에, count가 10억 + 7 이내의 값일 것이라 생각하신 것 같은데 그렇지는 않습니다.
계속 누적해서 덧셈을 하기 때문에 count가 10억 + 7 이상의 값을 가질 수 있죠

`count = (count % 1000000007) + (right - left + 1) % 1000000007;`

위와 같은 방법으로 계산해보시겠어요?
모듈러 연산은 분배법칙이 성립해서 `(A + B) % MOD = (A % MOD) + (B % MOD)`가 성립합니다.
물론 뺄셈의 경우에도 성립하구요. 모듈러 산술을 검색해보시면 나올거에요 ㅎㅎㅎ

그리고 영역을 구분 지을 때 [ left ] [ middle ] [ right ] 이런 식으로 구분지을 것 같은데.. leftSum이 그러면 prefixSums[i-1]이 되어야 하지 않나요 ? 그렇다면 `binarySearch` 함수의 l과 r의 값도 변경되어야 할 것 같습니다.

코드 수정은 다음과 같이 했습니다. 수정하다 잘 안되시면 한 번 참고해보세요..!

http://colorscripter.com/s/5DcfsV3

**Comment by hyejinhong** [comment]
@sonsy0929 해결되었습니다 감사합니다~~!~!
